
spring:
  application:
    name: shop-api
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
server:
  port: 8081
