
spring:
  application:
    name: shop-gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
        service: shop-gateway
    gateway:
      routes:
        - id: shop-api-route
          uri: lb://shop-api/**
          predicates:
            - Path=/api
        - id: shop-provider-route
          uri: lb://shop-provider
          predicates:
            - Path=/provider/**
      discovery:
        locator:
          enabled: true


server:
  port: 8082